export const storeProducts = [
    {
      id: 1,
      title: "Air Jordan 1 Elevate Low",
      firstImage: "assets/img/product-1/Air Jordan 1 Elevate Low - first.png",
      price: 259.90,
      company: "NIKE",
      info: "Rise to the occasion in style that soars. This shoe reworks an icon's original magic with a platform sole and low-cut silhouette. Air cushioning keeps you lifted, and sleek leather in contrasting colours adds visual interest"
    },
    {
      id: 2,
      title: "Air Jordan 1 Elevate Low SE",
      firstImage: "assets/img/product-2/Air Jordan 1 Elevate Low SE - first.png",
      price: 139.90,
      company: "NIKE",
      info:"The Air Jordan 1 Elevate takes the Air Jordan 1 Low and adds a chunky platform sole for a bold and unconventional look. This pair arrives in a blue and white colour scheme, crafted from leather and highlited by a Swoosh logo on the sides. Underneath, the midsole powered by Nike Air cushioning technology adds more comfort this low-top silhouette.",
    },
    {
      id: 3,
      title: "Air Jordan 1 Hi FlyEase",
      firstImage: "assets/img/product-3/Air Jordan 1 Hi FlyEase - first.png",
      price: 199.90,
      company: "NIKE",
      info: "The Air Jordan 1 Hi FlyEase combines the coveted style of Michael Jordan's first signature sneaker with a quick and easy one-handed entry system. There are no laces to tie, just a wraparound zip and two straps to secure a custom fit.",
    },
    {
      id: 4,
      title: "Air Jordan 1 Low FlyEase",
      firstImage: "assets/img/product-4/Air Jordan 1 Low FlyEase - first.png",
      price: 219.90,
      company: "NIKE",
      info: "Lock in your style with this AJ1. We kept everything you love about the classic design—premium leather, Air cushioning, iconic Wings logo—while adding the Nike FlyEase closure system to make on and off a breeze. Getting out the door is now quicker than ever: just strap and zip.",
    },
    {
      id: 5,
      title: "Jordan Series ES Men's Shoes",
      firstImage: "assets/img/product-5/Jordan Series ES Men's Shoes - first.png",
      price: 130.90,
      company: "NIKE",
      info: "Inspired by Mike's backyard battles with his older brother Larry, the Jordan Series references their legendary sibling rivalry throughout the design. The rubber sole offers more than just impressive traction—it also tells the story of how MJ came to be #23. Look for the hidden reminder to 'Swing for the Fence', a direct quote from Larry to his little bro.",
    },
    {
      id: 6,
      title: "Nike Dunk High 1985",
      firstImage: "assets/img/product-6/Nike Dunk High 1985 - first.png",
      price: 155.90,
      company: "NIKE",
      info: "Celebrate heritage with an updated version of the Dunk High, recrafted to reflect the original from 1985. Matching the shape, look and feel that started it all, it delivers true vintage style while keeping the familiar comfort you love.",
    },
    {
      id: 7,
      title: "Nike Dunk High Retro",
      firstImage: "assets/img/product-7/Nike Dunk High Retro - first.png",
      price: 267.90,
      company: "NIKE",
      info: "A basketball silhouette, the Nike Dunk Retro is presented in a supportive high-top design here. Contrasting white and black tones create an effortlessly eye-catching look for the pair.",
    },
    {
      id: 8,
      title: "Nike Waffle One - women",
      firstImage: "assets/img/product-8/Nike Waffle One - first.png",
      price: 168.90,
      company: "NIKE",
      info: "Bringing a new look to the iconic Waffle franchise, the Nike Waffle One balances everything you love most about heritage Nike running with fresh innovations. Its new durable plastic heel clip adds energy, while a mixture of transparent mesh and luscious suedes get you ready for summertime. The new springy midsole features the classic wedge shape while the updated Waffle outsole provides a level of support and traction you have to feel to believe.",
    }
  ];